// <auto-generated />
using System;
using AlanApiFilme;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlanApiFilme.Migrations
{
    [DbContext(typeof(DataBaseDbContext))]
    [Migration("20240621022825_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AlanApiFilme.Model.Filme", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaID")
                        .IsUnicode(false)
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClassificacaoID")
                        .IsUnicode(false)
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GeneroID")
                        .IsUnicode(false)
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MidiaID")
                        .IsUnicode(false)
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<Guid>("TipoMidiaID")
                        .IsUnicode(false)
                        .HasColumnType("char(36)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FILMES", (string)null);
                });

            modelBuilder.Entity("AlanApiFilme.Model.Participante", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("Participante");
                });

            modelBuilder.Entity("FilmeParticipante", b =>
                {
                    b.Property<Guid>("FilmesID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Participantesid")
                        .HasColumnType("char(36)");

                    b.HasKey("FilmesID", "Participantesid");

                    b.HasIndex("Participantesid");

                    b.ToTable("FilmeParticipante");
                });

            modelBuilder.Entity("FilmeParticipante", b =>
                {
                    b.HasOne("AlanApiFilme.Model.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlanApiFilme.Model.Participante", null)
                        .WithMany()
                        .HasForeignKey("Participantesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
